// Code generated by tmp/gen. DO NOT EDIT.

package narrationaudit

import "github.com/dmikalova/vex/internal/engine"

// EconomyResolver.

func (a *Auditor) CancelCurrentForge() {
	defer a.audit("CancelCurrentForge")()
	a.Game.CancelCurrentForge()
}

func (a *Auditor) EmitAemberStolenFrom(p0 int, p1 int) {
	defer a.audit("EmitAemberStolenFrom")()
	a.Game.EmitAemberStolenFrom(p0, p1)
}

func (a *Auditor) ForgeKeyAtExtraCost(p0 int, p1 int) bool {
	defer a.audit("ForgeKeyAtExtraCost")()
	return a.Game.ForgeKeyAtExtraCost(p0, p1)
}

func (a *Auditor) ForgeKeyFree(p0 int) bool {
	defer a.audit("ForgeKeyFree")()
	return a.Game.ForgeKeyFree(p0)
}

func (a *Auditor) ForgeKeyFreeForced(p0 int) bool {
	defer a.audit("ForgeKeyFreeForced")()
	return a.Game.ForgeKeyFreeForced(p0)
}

func (a *Auditor) GainAember(p0 int, p1 int) (engine.LocalID, bool) {
	defer a.audit("GainAember")()
	return a.Game.GainAember(p0, p1)
}

func (a *Auditor) GainChains(p0 int, p1 int) {
	defer a.audit("GainChains")()
	a.Game.GainChains(p0, p1)
}

func (a *Auditor) NoteAemberStolenFrom(p0 int, p1 int) {
	defer a.audit("NoteAemberStolenFrom")()
	a.Game.NoteAemberStolenFrom(p0, p1)
}

func (a *Auditor) RaiseKeyCostNextTurn(p0 int, p1 int, p2 engine.LocalID) {
	defer a.audit("RaiseKeyCostNextTurn")()
	a.Game.RaiseKeyCostNextTurn(p0, p1, p2)
}

func (a *Auditor) RaiseKeyCostPerHouseNextTurn(p0 int, p1 int, p2 engine.HouseMatcher, p3 engine.LocalID) {
	defer a.audit("RaiseKeyCostPerHouseNextTurn")()
	a.Game.RaiseKeyCostPerHouseNextTurn(p0, p1, p2, p3)
}

func (a *Auditor) RaiseKeyCostThisTurn(p0 int, p1 int, p2 engine.LocalID) {
	defer a.audit("RaiseKeyCostThisTurn")()
	a.Game.RaiseKeyCostThisTurn(p0, p1, p2)
}

func (a *Auditor) SetAember(p0 int, p1 int) {
	defer a.audit("SetAember")()
	a.Game.SetAember(p0, p1)
}

func (a *Auditor) StolenAemberCaptor(p0 int) (engine.LocalID, engine.LocalID, bool) {
	defer a.audit("StolenAemberCaptor")()
	return a.Game.StolenAemberCaptor(p0)
}

func (a *Auditor) UnforgeKey(p0 int) bool {
	defer a.audit("UnforgeKey")()
	return a.Game.UnforgeKey(p0)
}

// CreatureResolver.

func (a *Auditor) AddAmberOn(p0 engine.LocalID, p1 int) {
	defer a.audit("AddAmberOn")()
	a.Game.AddAmberOn(p0, p1)
}

func (a *Auditor) AddPowerCounter(p0 engine.LocalID, p1 int) {
	defer a.audit("AddPowerCounter")()
	a.Game.AddPowerCounter(p0, p1)
}

func (a *Auditor) BelongToHouseForRemainderOfTurn(p0 engine.LocalID, p1 engine.House) {
	defer a.audit("BelongToHouseForRemainderOfTurn")()
	a.Game.BelongToHouseForRemainderOfTurn(p0, p1)
}

func (a *Auditor) ConsiderFlank(p0 engine.LocalID) {
	defer a.audit("ConsiderFlank")()
	a.Game.ConsiderFlank(p0)
}

func (a *Auditor) CopyStats(p0 engine.LocalID, p1 engine.LocalID) {
	defer a.audit("CopyStats")()
	a.Game.CopyStats(p0, p1)
}

func (a *Auditor) GainAssault(p0 engine.LocalID, p1 int) {
	defer a.audit("GainAssault")()
	a.Game.GainAssault(p0, p1)
}

func (a *Auditor) GainStats(p0 engine.LocalID, p1 int, p2 int) {
	defer a.audit("GainStats")()
	a.Game.GainStats(p0, p1, p2)
}

func (a *Auditor) GrantAssaultUntilNextTurn(p0 engine.LocalID, p1 int) {
	defer a.audit("GrantAssaultUntilNextTurn")()
	a.Game.GrantAssaultUntilNextTurn(p0, p1)
}

func (a *Auditor) GrantKeyword(p0 engine.LocalID, p1 engine.Keyword) {
	defer a.audit("GrantKeyword")()
	a.Game.GrantKeyword(p0, p1)
}

func (a *Auditor) GrantKeywordUntilNextTurn(p0 engine.LocalID, p1 engine.Keyword) {
	defer a.audit("GrantKeywordUntilNextTurn")()
	a.Game.GrantKeywordUntilNextTurn(p0, p1)
}

func (a *Auditor) GrantTextBox(p0 engine.LocalID, p1 engine.LocalID, p2 engine.Duration) {
	defer a.audit("GrantTextBox")()
	a.Game.GrantTextBox(p0, p1, p2)
}

func (a *Auditor) GrantTraitUntilNextTurn(p0 engine.LocalID, p1 engine.Trait) {
	defer a.audit("GrantTraitUntilNextTurn")()
	a.Game.GrantTraitUntilNextTurn(p0, p1)
}

func (a *Auditor) LoseKeyword(p0 engine.Keyword) {
	defer a.audit("LoseKeyword")()
	a.Game.LoseKeyword(p0)
}

func (a *Auditor) LoseKeywordFrom(p0 engine.LocalID, p1 engine.Keyword) {
	defer a.audit("LoseKeywordFrom")()
	a.Game.LoseKeywordFrom(p0, p1)
}

func (a *Auditor) LoseKeywordUntilNextTurn(p0 engine.LocalID, p1 engine.Keyword) {
	defer a.audit("LoseKeywordUntilNextTurn")()
	a.Game.LoseKeywordUntilNextTurn(p0, p1)
}

func (a *Auditor) MoveToFlank(p0 engine.LocalID, p1 bool) {
	defer a.audit("MoveToFlank")()
	a.Game.MoveToFlank(p0, p1)
}

func (a *Auditor) MoveWithinBattleline(p0 int, p1 engine.LocalID) {
	defer a.audit("MoveWithinBattleline")()
	a.Game.MoveWithinBattleline(p0, p1)
}

func (a *Auditor) PlaceCounter(p0 engine.LocalID, p1 engine.CounterKind, p2 int) {
	defer a.audit("PlaceCounter")()
	a.Game.PlaceCounter(p0, p1, p2)
}

func (a *Auditor) PutIntoBattlelineAsCreature(p0 engine.LocalID, p1 bool, p2 engine.Duration) {
	defer a.audit("PutIntoBattlelineAsCreature")()
	a.Game.PutIntoBattlelineAsCreature(p0, p1, p2)
}

func (a *Auditor) RemoveCounters(p0 engine.LocalID, p1 engine.CounterKind) {
	defer a.audit("RemoveCounters")()
	a.Game.RemoveCounters(p0, p1)
}

func (a *Auditor) RemoveCountersN(p0 engine.LocalID, p1 engine.CounterKind, p2 int) {
	defer a.audit("RemoveCountersN")()
	a.Game.RemoveCountersN(p0, p1, p2)
}

func (a *Auditor) SetDamage(p0 engine.LocalID, p1 int) {
	defer a.audit("SetDamage")()
	a.Game.SetDamage(p0, p1)
}

func (a *Auditor) SetDamageImmune(p0 engine.LocalID, p1 engine.Duration) {
	defer a.audit("SetDamageImmune")()
	a.Game.SetDamageImmune(p0, p1)
}

func (a *Auditor) SetEnraged(p0 engine.LocalID, p1 bool) {
	defer a.audit("SetEnraged")()
	a.Game.SetEnraged(p0, p1)
}

func (a *Auditor) SetExhausted(p0 engine.LocalID, p1 bool) {
	defer a.audit("SetExhausted")()
	a.Game.SetExhausted(p0, p1)
}

func (a *Auditor) SetLastingHouse(p0 engine.LocalID, p1 engine.House) {
	defer a.audit("SetLastingHouse")()
	a.Game.SetLastingHouse(p0, p1)
}

func (a *Auditor) SetNamedCard(p0 engine.LocalID, p1 engine.LocalID) {
	defer a.audit("SetNamedCard")()
	a.Game.SetNamedCard(p0, p1)
}

func (a *Auditor) SetNamedHouse(p0 engine.LocalID, p1 engine.House) {
	defer a.audit("SetNamedHouse")()
	a.Game.SetNamedHouse(p0, p1)
}

func (a *Auditor) SetSideDamageImmune(p0 int, p1 engine.Duration) {
	defer a.audit("SetSideDamageImmune")()
	a.Game.SetSideDamageImmune(p0, p1)
}

func (a *Auditor) SetStatOverride(p0 engine.StatMask, p1 engine.StatMask, p2 engine.Duration) {
	defer a.audit("SetStatOverride")()
	a.Game.SetStatOverride(p0, p1, p2)
}

func (a *Auditor) SetStunned(p0 engine.LocalID, p1 bool) {
	defer a.audit("SetStunned")()
	a.Game.SetStunned(p0, p1)
}

func (a *Auditor) SetWarded(p0 engine.LocalID, p1 bool) {
	defer a.audit("SetWarded")()
	a.Game.SetWarded(p0, p1)
}

func (a *Auditor) StripArmor(p0 engine.LocalID) {
	defer a.audit("StripArmor")()
	a.Game.StripArmor(p0)
}

func (a *Auditor) SwapCards(p0 engine.LocalID, p1 engine.LocalID) {
	defer a.audit("SwapCards")()
	a.Game.SwapCards(p0, p1)
}

func (a *Auditor) TakeControl(p0 engine.LocalID, p1 int, p2 engine.LocalID) {
	defer a.audit("TakeControl")()
	a.Game.TakeControl(p0, p1, p2)
}

// CombatResolver.

func (a *Auditor) AtRuleOfSix(p0 engine.LocalID) bool {
	defer a.audit("AtRuleOfSix")()
	return a.Game.AtRuleOfSix(p0)
}

func (a *Auditor) CancelCurrentFight() {
	defer a.audit("CancelCurrentFight")()
	a.Game.CancelCurrentFight()
}

func (a *Auditor) DealDamage(p0 int, p1 []engine.DamageTarget) {
	defer a.audit("DealDamage")()
	a.Game.DealDamage(p0, p1)
}

func (a *Auditor) DestroyEach(p0 int, p1 []engine.LocalID) {
	defer a.audit("DestroyEach")()
	a.Game.DestroyEach(p0, p1)
}

func (a *Auditor) DestroyEachFrom(p0 int, p1 engine.LocalID, p2 []engine.LocalID) {
	defer a.audit("DestroyEachFrom")()
	a.Game.DestroyEachFrom(p0, p1, p2)
}

func (a *Auditor) FightWith(p0 engine.LocalID, p1 engine.LocalID) {
	defer a.audit("FightWith")()
	a.Game.FightWith(p0, p1)
}

func (a *Auditor) ProtectedByTaunt(p0 engine.LocalID, p1 engine.LocalID) bool {
	defer a.audit("ProtectedByTaunt")()
	return a.Game.ProtectedByTaunt(p0, p1)
}

func (a *Auditor) ReapWith(p0 engine.LocalID) {
	defer a.audit("ReapWith")()
	a.Game.ReapWith(p0)
}

func (a *Auditor) RecordUsage(p0 engine.LocalID) {
	defer a.audit("RecordUsage")()
	a.Game.RecordUsage(p0)
}

func (a *Auditor) SetFightDamageRedirect(p0 engine.LocalID) {
	defer a.audit("SetFightDamageRedirect")()
	a.Game.SetFightDamageRedirect(p0)
}

func (a *Auditor) TriggerAbilityOf(p0 int, p1 engine.LocalID, p2 engine.Trigger) {
	defer a.audit("TriggerAbilityOf")()
	a.Game.TriggerAbilityOf(p0, p1, p2)
}

func (a *Auditor) TriggerAbilityOfRooted(p0 int, p1 engine.LocalID, p2 engine.Trigger, p3 engine.LocalID) {
	defer a.audit("TriggerAbilityOfRooted")()
	a.Game.TriggerAbilityOfRooted(p0, p1, p2, p3)
}

func (a *Auditor) UseActionOf(p0 int, p1 engine.LocalID) {
	defer a.audit("UseActionOf")()
	a.Game.UseActionOf(p0, p1)
}

// ZoneResolver.

func (a *Auditor) ArchiveCardUnder(p0 engine.LocalID) {
	defer a.audit("ArchiveCardUnder")()
	a.Game.ArchiveCardUnder(p0)
}

func (a *Auditor) ArchiveEnemyFromHand(p0 int, p1 engine.LocalID) {
	defer a.audit("ArchiveEnemyFromHand")()
	a.Game.ArchiveEnemyFromHand(p0, p1)
}

func (a *Auditor) ArchiveFromDeck(p0 engine.LocalID) {
	defer a.audit("ArchiveFromDeck")()
	a.Game.ArchiveFromDeck(p0)
}

func (a *Auditor) ArchiveFromDiscard(p0 int, p1 engine.LocalID) {
	defer a.audit("ArchiveFromDiscard")()
	a.Game.ArchiveFromDiscard(p0, p1)
}

func (a *Auditor) ArchiveFromHand(p0 engine.LocalID) {
	defer a.audit("ArchiveFromHand")()
	a.Game.ArchiveFromHand(p0)
}

func (a *Auditor) ArchiveFromPurge(p0 int, p1 engine.LocalID) {
	defer a.audit("ArchiveFromPurge")()
	a.Game.ArchiveFromPurge(p0, p1)
}

func (a *Auditor) ArchiveUpgrade(p0 engine.LocalID) {
	defer a.audit("ArchiveUpgrade")()
	a.Game.ArchiveUpgrade(p0)
}

func (a *Auditor) BeginShuffleBatch() {
	defer a.audit("BeginShuffleBatch")()
	a.Game.BeginShuffleBatch()
}

func (a *Auditor) DiscardArchives(p0 int) {
	defer a.audit("DiscardArchives")()
	a.Game.DiscardArchives(p0)
}

func (a *Auditor) DiscardCardFromArchives(p0 int, p1 engine.LocalID) {
	defer a.audit("DiscardCardFromArchives")()
	a.Game.DiscardCardFromArchives(p0, p1)
}

func (a *Auditor) DiscardCardFromHand(p0 int, p1 engine.LocalID) {
	defer a.audit("DiscardCardFromHand")()
	a.Game.DiscardCardFromHand(p0, p1)
}

func (a *Auditor) DiscardTopOfDeck(p0 int) (engine.LocalID, bool) {
	defer a.audit("DiscardTopOfDeck")()
	return a.Game.DiscardTopOfDeck(p0)
}

func (a *Auditor) Draw(p0 int, p1 int) {
	defer a.audit("Draw")()
	a.Game.Draw(p0, p1)
}

func (a *Auditor) EndShuffleBatch() {
	defer a.audit("EndShuffleBatch")()
	a.Game.EndShuffleBatch()
}

func (a *Auditor) GraftUnder(p0 engine.LocalID, p1 engine.LocalID) {
	defer a.audit("GraftUnder")()
	a.Game.GraftUnder(p0, p1)
}

func (a *Auditor) MoveFromDeckToDiscard(p0 engine.LocalID) {
	defer a.audit("MoveFromDeckToDiscard")()
	a.Game.MoveFromDeckToDiscard(p0)
}

func (a *Auditor) MoveFromDeckToHand(p0 engine.LocalID) {
	defer a.audit("MoveFromDeckToHand")()
	a.Game.MoveFromDeckToHand(p0)
}

func (a *Auditor) MoveFromDeckToTopOfDeck(p0 engine.LocalID) {
	defer a.audit("MoveFromDeckToTopOfDeck")()
	a.Game.MoveFromDeckToTopOfDeck(p0)
}

func (a *Auditor) MoveFromDiscardToTopOfDeck(p0 engine.LocalID) {
	defer a.audit("MoveFromDiscardToTopOfDeck")()
	a.Game.MoveFromDiscardToTopOfDeck(p0)
}

func (a *Auditor) MoveUpgrade(p0 engine.LocalID, p1 engine.LocalID) {
	defer a.audit("MoveUpgrade")()
	a.Game.MoveUpgrade(p0, p1)
}

func (a *Auditor) PlayFromArchives(p0 int, p1 engine.LocalID) {
	defer a.audit("PlayFromArchives")()
	a.Game.PlayFromArchives(p0, p1)
}

func (a *Auditor) PlayFromDeck(p0 int, p1 engine.LocalID) {
	defer a.audit("PlayFromDeck")()
	a.Game.PlayFromDeck(p0, p1)
}

func (a *Auditor) PlayFromDiscard(p0 int, p1 engine.LocalID) {
	defer a.audit("PlayFromDiscard")()
	a.Game.PlayFromDiscard(p0, p1)
}

func (a *Auditor) PlayFromHand(p0 int, p1 engine.LocalID) {
	defer a.audit("PlayFromHand")()
	a.Game.PlayFromHand(p0, p1)
}

func (a *Auditor) PlayFromOpponent(p0 int, p1 engine.Zone) {
	defer a.audit("PlayFromOpponent")()
	a.Game.PlayFromOpponent(p0, p1)
}

func (a *Auditor) PlayFromOpponentDiscard(p0 int, p1 engine.LocalID) {
	defer a.audit("PlayFromOpponentDiscard")()
	a.Game.PlayFromOpponentDiscard(p0, p1)
}

func (a *Auditor) PlayFromOpponentHand(p0 int, p1 engine.LocalID) {
	defer a.audit("PlayFromOpponentHand")()
	a.Game.PlayFromOpponentHand(p0, p1)
}

func (a *Auditor) PlayFromUnder(p0 int, p1 engine.LocalID) {
	defer a.audit("PlayFromUnder")()
	a.Game.PlayFromUnder(p0, p1)
}

func (a *Auditor) PurgeFromArchives(p0 int, p1 engine.LocalID) {
	defer a.audit("PurgeFromArchives")()
	a.Game.PurgeFromArchives(p0, p1)
}

func (a *Auditor) PurgeFromDeck(p0 int, p1 engine.LocalID) {
	defer a.audit("PurgeFromDeck")()
	a.Game.PurgeFromDeck(p0, p1)
}

func (a *Auditor) PurgeFromDiscard(p0 int, p1 engine.LocalID) {
	defer a.audit("PurgeFromDiscard")()
	a.Game.PurgeFromDiscard(p0, p1)
}

func (a *Auditor) PurgeFromHand(p0 int, p1 engine.LocalID) {
	defer a.audit("PurgeFromHand")()
	a.Game.PurgeFromHand(p0, p1)
}

func (a *Auditor) PurgeFromPlay(p0 engine.LocalID) {
	defer a.audit("PurgeFromPlay")()
	a.Game.PurgeFromPlay(p0)
}

func (a *Auditor) PutCardUnder(p0 int, p1 engine.LocalID, p2 engine.LocalID, p3 bool) {
	defer a.audit("PutCardUnder")()
	a.Game.PutCardUnder(p0, p1, p2, p3)
}

func (a *Auditor) PutDeckCardOnBottom(p0 engine.LocalID) {
	defer a.audit("PutDeckCardOnBottom")()
	a.Game.PutDeckCardOnBottom(p0)
}

func (a *Auditor) PutFromDiscardIntoHand(p0 engine.LocalID) {
	defer a.audit("PutFromDiscardIntoHand")()
	a.Game.PutFromDiscardIntoHand(p0)
}

func (a *Auditor) PutIntoArchives(p0 engine.LocalID) {
	defer a.audit("PutIntoArchives")()
	a.Game.PutIntoArchives(p0)
}

func (a *Auditor) PutIntoArchivesEach(p0 int, p1 []engine.LocalID) {
	defer a.audit("PutIntoArchivesEach")()
	a.Game.PutIntoArchivesEach(p0, p1)
}

func (a *Auditor) PutIntoDeckShuffled(p0 engine.LocalID) {
	defer a.audit("PutIntoDeckShuffled")()
	a.Game.PutIntoDeckShuffled(p0)
}

func (a *Auditor) PutIntoHand(p0 engine.LocalID) {
	defer a.audit("PutIntoHand")()
	a.Game.PutIntoHand(p0)
}

func (a *Auditor) PutIntoPlay(p0 engine.LocalID, p1 int) {
	defer a.audit("PutIntoPlay")()
	a.Game.PutIntoPlay(p0, p1)
}

func (a *Auditor) PutIntoYourArchives(p0 engine.LocalID, p1 int) {
	defer a.audit("PutIntoYourArchives")()
	a.Game.PutIntoYourArchives(p0, p1)
}

func (a *Auditor) PutOnTopOfDeck(p0 engine.LocalID) {
	defer a.audit("PutOnTopOfDeck")()
	a.Game.PutOnTopOfDeck(p0)
}

func (a *Auditor) PutUnderIntoPlay(p0 engine.LocalID) {
	defer a.audit("PutUnderIntoPlay")()
	a.Game.PutUnderIntoPlay(p0)
}

func (a *Auditor) RedirectResolvingCard(p0 engine.LocalID, p1 engine.Destination) {
	defer a.audit("RedirectResolvingCard")()
	a.Game.RedirectResolvingCard(p0, p1)
}

func (a *Auditor) RefillHand(p0 int) {
	defer a.audit("RefillHand")()
	a.Game.RefillHand(p0)
}

func (a *Auditor) ResolveBonusIconsOn(p0 int, p1 engine.LocalID) {
	defer a.audit("ResolveBonusIconsOn")()
	a.Game.ResolveBonusIconsOn(p0, p1)
}

func (a *Auditor) SetDeckTop(p0 int, p1 []engine.LocalID) {
	defer a.audit("SetDeckTop")()
	a.Game.SetDeckTop(p0, p1)
}

func (a *Auditor) Shuffle(p0 int) {
	defer a.audit("Shuffle")()
	a.Game.Shuffle(p0)
}

func (a *Auditor) ShuffleFromDiscardIntoDeck(p0 engine.LocalID) {
	defer a.audit("ShuffleFromDiscardIntoDeck")()
	a.Game.ShuffleFromDiscardIntoDeck(p0)
}

func (a *Auditor) ShuffleFromHandIntoDeck(p0 engine.LocalID) {
	defer a.audit("ShuffleFromHandIntoDeck")()
	a.Game.ShuffleFromHandIntoDeck(p0)
}

func (a *Auditor) ShuffleZonesIntoDeck(p0 int, p1 []engine.Zone) {
	defer a.audit("ShuffleZonesIntoDeck")()
	a.Game.ShuffleZonesIntoDeck(p0, p1)
}

func (a *Auditor) Simultaneously(p0 int, p1 func()) {
	defer a.audit("Simultaneously")()
	a.Game.Simultaneously(p0, p1)
}

func (a *Auditor) SwapDeckAndDiscard(p0 int) {
	defer a.audit("SwapDeckAndDiscard")()
	a.Game.SwapDeckAndDiscard(p0)
}

// TurnResolver.

func (a *Auditor) AddLasting(p0 engine.LastingEffect) {
	defer a.audit("AddLasting")()
	a.Game.AddLasting(p0)
}

func (a *Auditor) AddLastingAlsoTriggers(p0 engine.LastingAlsoTriggersOn) {
	defer a.audit("AddLastingAlsoTriggers")()
	a.Game.AddLastingAlsoTriggers(p0)
}

func (a *Auditor) BlankEnemyText(p0 int) {
	defer a.audit("BlankEnemyText")()
	a.Game.BlankEnemyText(p0)
}

func (a *Auditor) CannotChooseHouseNextTurn(p0 int, p1 engine.House, p2 engine.LocalID) {
	defer a.audit("CannotChooseHouseNextTurn")()
	a.Game.CannotChooseHouseNextTurn(p0, p1, p2)
}

func (a *Auditor) CannotFightNextTurn(p0 int, p1 engine.LocalID) {
	defer a.audit("CannotFightNextTurn")()
	a.Game.CannotFightNextTurn(p0, p1)
}

func (a *Auditor) CannotPlayTypeNextTurn(p0 int, p1 engine.CardType, p2 engine.LocalID) {
	defer a.audit("CannotPlayTypeNextTurn")()
	a.Game.CannotPlayTypeNextTurn(p0, p1, p2)
}

func (a *Auditor) CannotPlayTypeThisTurn(p0 int, p1 engine.CardType, p2 engine.LocalID) {
	defer a.audit("CannotPlayTypeThisTurn")()
	a.Game.CannotPlayTypeThisTurn(p0, p1, p2)
}

func (a *Auditor) CannotReapHouseNextTurn(p0 int, p1 engine.House, p2 engine.LocalID) {
	defer a.audit("CannotReapHouseNextTurn")()
	a.Game.CannotReapHouseNextTurn(p0, p1, p2)
}

func (a *Auditor) CannotReapNextTurn(p0 int, p1 engine.LocalID) {
	defer a.audit("CannotReapNextTurn")()
	a.Game.CannotReapNextTurn(p0, p1)
}

func (a *Auditor) CannotReapThisTurn(p0 int, p1 engine.LocalID) {
	defer a.audit("CannotReapThisTurn")()
	a.Game.CannotReapThisTurn(p0, p1)
}

func (a *Auditor) CannotUseNextTurn(p0 int, p1 engine.LocalID) {
	defer a.audit("CannotUseNextTurn")()
	a.Game.CannotUseNextTurn(p0, p1)
}

func (a *Auditor) CannotUseThisTurn(p0 int, p1 engine.LocalID) {
	defer a.audit("CannotUseThisTurn")()
	a.Game.CannotUseThisTurn(p0, p1)
}

func (a *Auditor) CreaturesCannotUntilNextTurn(p0 int, p1 engine.UseKind, p2 engine.HouseMatcher, p3 engine.LocalID) {
	defer a.audit("CreaturesCannotUntilNextTurn")()
	a.Game.CreaturesCannotUntilNextTurn(p0, p1, p2, p3)
}

func (a *Auditor) EndTurnNow() {
	defer a.audit("EndTurnNow")()
	a.Game.EndTurnNow()
}

func (a *Auditor) GrantMayPlayOrUse(p0 int, p1 engine.HouseSelector, p2 engine.HouseGrant, p3 engine.CardTypes, p4 int) {
	defer a.audit("GrantMayPlayOrUse")()
	a.Game.GrantMayPlayOrUse(p0, p1, p2, p3, p4)
}

func (a *Auditor) GrantMayUseTrait(p0 int, p1 engine.Trait) {
	defer a.audit("GrantMayUseTrait")()
	a.Game.GrantMayUseTrait(p0, p1)
}

func (a *Auditor) MustChooseFoughtHouseNextTurn(p0 int, p1 engine.LocalID, p2 engine.LocalID) {
	defer a.audit("MustChooseFoughtHouseNextTurn")()
	a.Game.MustChooseFoughtHouseNextTurn(p0, p1, p2)
}

func (a *Auditor) MustChooseHouseNextTurn(p0 int, p1 engine.House, p2 engine.LocalID) {
	defer a.audit("MustChooseHouseNextTurn")()
	a.Game.MustChooseHouseNextTurn(p0, p1, p2)
}

func (a *Auditor) ScheduleAtEndOfTurn(p0 engine.LocalID, p1 engine.ScheduledAction) {
	defer a.audit("ScheduleAtEndOfTurn")()
	a.Game.ScheduleAtEndOfTurn(p0, p1)
}

func (a *Auditor) ScheduleOnLeave(p0 engine.LocalID, p1 engine.ScheduledAction) {
	defer a.audit("ScheduleOnLeave")()
	a.Game.ScheduleOnLeave(p0, p1)
}

func (a *Auditor) SetActiveHouse(p0 engine.House) {
	defer a.audit("SetActiveHouse")()
	a.Game.SetActiveHouse(p0)
}

func (a *Auditor) SkipForgePhaseNextTurn(p0 int, p1 engine.LocalID) {
	defer a.audit("SkipForgePhaseNextTurn")()
	a.Game.SkipForgePhaseNextTurn(p0, p1)
}

func (a *Auditor) WagerOnHouseNextTurn(p0 int, p1 engine.House, p2 int, p3 int, p4 engine.LocalID) {
	defer a.audit("WagerOnHouseNextTurn")()
	a.Game.WagerOnHouseNextTurn(p0, p1, p2, p3, p4)
}

// 139 wrappers.
